name: RawBuildTest
on: [push]
jobs:
  BuildKali:
    name: build impish
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Satify Dependencies
        run: sudo apt update; sudo apt install git build-essential binfmt-support qemu-user-static debootstrap -y
      
      - name: Trigger fs-cook
        run: bash .github/scripts/kali.sh
      
      - name: save arm64 builds
        uses: actions/upload-artifact@v2
        with:
          name: kali-rolling-big-arm64
          path: kali-rolling-arm64
      
      - name: save armhf builds
        uses: actions/upload-artifact@v2
        with:
          name: kali-rolling-big-armhf
          path: kali-rolling-armhf
      
      - name: save amd64 builds
        uses: actions/upload-artifact@v2
        with:
          name: kali-rolling-big-amd64
          path: kali-rolling-amd64
